-- require('lspconfig').rust_analyzer.setup({
--     -- Uncomment for embedded work
--     --settings = {
--     --    ["rust-analyzer"] = {
--     --        checkOnSave = {
--     --            allTargets = false,
--     --            extraArgs = { "--bins" },
--     --        },
--     --    }
--     --}
-- })

-- require('lspconfig').rust_analyzer.setup({
--     settings = {
--         ["rust-analyzer"] = {
--             cargo = {
--                 allFeatures = true,
--             },
--         }
--     }
-- })
